/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ine5612.View;

import ine5612.Controllers.FuncionaryController;
import ine5612.Controllers.ManagerController;
import ine5612.Model.UserModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Calza
 */
public class ComandaPanel extends javax.swing.JPanel {
    FuncionaryController funcionaryController;
    ManagerController managerController;
    
    /**
     * Creates new form ComandaPanel
     */
    public ComandaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        editCommand = new javax.swing.JButton();
        closeCommandPanel = new javax.swing.JButton();

        clienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", ""},
                {"2", null},
                {"3", null},
                {"4", null},
                {"5", null},
                {"6", null}
            },
            new String [] {
                "Comanda", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clienteTable);

        editCommand.setText("Editar Comanda");
        editCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCommandActionPerformed(evt);
            }
        });

        closeCommandPanel.setText("Fechar");
        closeCommandPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCommandPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeCommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editCommand)
                        .addGap(123, 123, 123)
                        .addComponent(closeCommandPanel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeCommandPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCommandPanelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeCommandPanelActionPerformed

    private void editCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCommandActionPerformed
        // TODO add your handling code here:
        int selectedRow = clienteTable.getSelectedRow();
        //abrir uma comanda para adicionar itens
        DefaultTableModel model = (DefaultTableModel) clienteTable.getModel();
        if(selectedRow==-1){
            JOptionPane.showMessageDialog(null, "Selecione a comanda de um cliente");
        }else{
                    new ManagerController();
        }

        //if(){//se for gerente
              //new ManagerController();
        //}else{//se for funcionario
            
        //}
    }//GEN-LAST:event_editCommandActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clienteTable;
    private javax.swing.JButton closeCommandPanel;
    private javax.swing.JButton editCommand;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
