/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ine5612.View;

import ine5612.Controllers.CommandController;
import ine5612.Controllers.FuncionaryController;
import ine5612.Model.UserModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ine5612.View.MainFrame;

/**
 *
 * @author Calza
 */
public class ComandaPanel extends javax.swing.JPanel {

    FuncionaryController funcionaryController;
    CommandController commandController;
    int selectedRow;

    /**
     * Creates new form ComandaPanel
     */
    public ComandaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        editCommandButton = new javax.swing.JButton();
        closeCommandPanelButton = new javax.swing.JButton();
        finalyzeCommandButton = new javax.swing.JButton();

        clienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null},
                {"2", null},
                {"3", null},
                {"4", null},
                {"5", null},
                {"6", null}
            },
            new String [] {
                "Comandas", "Valor R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clienteTable);
        if (clienteTable.getColumnModel().getColumnCount() > 0) {
            clienteTable.getColumnModel().getColumn(0).setResizable(false);
            clienteTable.getColumnModel().getColumn(1).setResizable(false);
        }

        editCommandButton.setText("Editar Comanda");
        editCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCommandButtonActionPerformed(evt);
            }
        });

        closeCommandPanelButton.setText("Fechar");
        closeCommandPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCommandPanelButtonActionPerformed(evt);
            }
        });

        finalyzeCommandButton.setText("Finalizar comanda");
        finalyzeCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalyzeCommandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(closeCommandPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(finalyzeCommandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editCommandButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editCommandButton)
                        .addGap(87, 87, 87)
                        .addComponent(finalyzeCommandButton)
                        .addGap(36, 36, 36)))
                .addGap(5, 5, 5)
                .addComponent(closeCommandPanelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeCommandPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCommandPanelButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_closeCommandPanelButtonActionPerformed

    private void editCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCommandButtonActionPerformed
        // TODO add your handling code here:
        selectedRow = clienteTable.getSelectedRow();

        //abrir uma comanda para adicionar itens
        DefaultTableModel model = (DefaultTableModel) clienteTable.getModel();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Selecione a comanda de um cliente");
        } else {
            commandController = new CommandController();
            commandController.openEditCommand();
        }

        //if(){//se for gerente
        //new ManagerController();
        //}else{//se for funcionario
        //}
    }//GEN-LAST:event_editCommandButtonActionPerformed

    public void setValueTabbleClient() {
        //TODO
        clienteTable.setValueAt(commandController.getSum(), selectedRow, 1);
    }

    private void finalyzeCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalyzeCommandButtonActionPerformed
        // TODO add your handling code here:
        //somente gerente pode fazer
        //if(userModel.isManager()){
        double finalValue = 0;
        DefaultTableModel model = (DefaultTableModel) clienteTable.getModel();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Selecione a comanda de um cliente");
        } else {
            if (commandController.getSum() != 0) {
                finalValue = commandController.getSum();
            }
            JOptionPane.showMessageDialog(null, "Comanda finalizada."
                    + "\n\n Total: "+finalValue+ "\n", "Finalização de comanda", 1);

        }

        //remover coisas da comanda
        //for(int i=comandaTable.getRowCount(); i>0;i--){
        //    model.removeRow(i-1);}
        //desabilitar opções de adicionar mais coisas em uma comanda após o
        //editCommandPanel.addToCommand.disable();
    }//GEN-LAST:event_finalyzeCommandButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clienteTable;
    private javax.swing.JButton closeCommandPanelButton;
    private javax.swing.JButton editCommandButton;
    private javax.swing.JButton finalyzeCommandButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
