/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ine5612.View;

import ine5612.Controllers.CommandController;
import ine5612.Controllers.FuncionaryController;
import ine5612.Model.UserModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ine5612.View.MainFrame;

/**
 *
 * @author Calza
 */
public class ComandaPanel extends javax.swing.JPanel {

    FuncionaryController funcionaryController;
    CommandController commandController;
    int selectedRow;
    DefaultTableModel modelClientTable;

    /**
     * Creates new form ComandaPanel
     */
    public ComandaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clienteTable = new javax.swing.JTable();
        editCommandButton = new javax.swing.JButton();
        closeCommandPanelButton = new javax.swing.JButton();
        finalyzeCommandButton = new javax.swing.JButton();
        addToClientTabbleButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameClienteTextField = new javax.swing.JTextField();
        nameFuncionaryTextField = new javax.swing.JTextField();

        clienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comanda", "Atendente", "Valor R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(clienteTable);
        if (clienteTable.getColumnModel().getColumnCount() > 0) {
            clienteTable.getColumnModel().getColumn(0).setResizable(false);
            clienteTable.getColumnModel().getColumn(1).setResizable(false);
            clienteTable.getColumnModel().getColumn(2).setResizable(false);
        }

        editCommandButton.setText("Editar Comanda");
        editCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCommandButtonActionPerformed(evt);
            }
        });

        closeCommandPanelButton.setText("Fechar");
        closeCommandPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCommandPanelButtonActionPerformed(evt);
            }
        });

        finalyzeCommandButton.setText("Finalizar comanda");
        finalyzeCommandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalyzeCommandButtonActionPerformed(evt);
            }
        });

        addToClientTabbleButton.setText("Adicionar comanda");
        addToClientTabbleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToClientTabbleButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Atendente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameFuncionaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addToClientTabbleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(closeCommandPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editCommandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalyzeCommandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameFuncionaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addToClientTabbleButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(editCommandButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalyzeCommandButton)
                        .addGap(41, 41, 41)
                        .addComponent(closeCommandPanelButton)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeCommandPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCommandPanelButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_closeCommandPanelButtonActionPerformed

    private void editCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCommandButtonActionPerformed
        // TODO add your handling code here:
        selectedRow = clienteTable.getSelectedRow();

        //abrir uma comanda para adicionar itens
        modelClientTable = (DefaultTableModel) clienteTable.getModel();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Selecione a comanda de um cliente");
        } else {
            commandController = new CommandController();
            commandController.openEditCommand();
        }

        //if(){//se for gerente
        //new ManagerController();
        //}else{//se for funcionario
        //}
    }//GEN-LAST:event_editCommandButtonActionPerformed

    /*public void setValueTabbleClient() {
        //TODO
        clienteTable.setValueAt(commandController.getSum(), selectedRow, 1);
    }*/

    private void finalyzeCommandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalyzeCommandButtonActionPerformed
        // TODO add your handling code here:
        //somente gerente pode fazer
        //if(userModel.isManager()){
        double finalValue = 0;
        modelClientTable = (DefaultTableModel) clienteTable.getModel();
        selectedRow = clienteTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Selecione a comanda de um cliente");
        } else {
            
            //commandController = new CommandController();
            finalValue = commandController.getSum();
            JOptionPane.showMessageDialog(null, "Comanda finalizada."
                    + "\n\n Total: " + finalValue + "\n", "Finalização de comanda", 1);
            modelClientTable.removeRow(selectedRow);
            }
           

        

        //remover coisas da comanda
        //for(int i=comandaTable.getRowCount(); i>0;i--){
        //    modelClientTable.removeRow(i-1);}
        //desabilitar opções de adicionar mais coisas em uma comanda após o
        //editCommandPanel.addToCommand.disable();
    }//GEN-LAST:event_finalyzeCommandButtonActionPerformed

    private void addToClientTabbleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToClientTabbleButtonActionPerformed
        // TODO add your handling code here:
        //String nome = userModel.getNome();
        modelClientTable = (DefaultTableModel) clienteTable.getModel();
        if (!nameClienteTextField.getText().trim().equals("")) {
            modelClientTable.addRow(new Object[]{nameClienteTextField.getText(), nameFuncionaryTextField.getText()});

        } else {
            JOptionPane.showMessageDialog(null, "Informe um cliente para iniciar a comanda");

        }

    }//GEN-LAST:event_addToClientTabbleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToClientTabbleButton;
    private javax.swing.JTable clienteTable;
    private javax.swing.JButton closeCommandPanelButton;
    private javax.swing.JButton editCommandButton;
    private javax.swing.JButton finalyzeCommandButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameClienteTextField;
    private javax.swing.JTextField nameFuncionaryTextField;
    // End of variables declaration//GEN-END:variables
}
